global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 2.0
  publish_frequency: 1.0
  width: 10.0
  height: 10.0
  resolution: 0.05
  static_map: true
  rolling_window: false
  transform_tolerance: 1