

TrajectoryPlannerROS:
  max_vel_x: 3.5 #0.5
  min_vel_x: -0.01 #0.01
  max_vel_theta: 3.0 #1.5

  min_in_place_vel_theta: 0.02

  acc_lim_theta: 4.14
  acc_lim_x: 4.0
  acc_lim_y: 4.0

  sim_time: 3.0
  vx_samples: 15.0
  vtheta_samples: 15.0
  meter_scoring: true

  path_distance_bias: 25 #0.6
  goal_distance_bias: 5 #0.8
  occdist_scale: 0.05
  latch_xy_goal_tolerance: false

  holonomic_robot: false


  shutdown_costmaps: false

  controller_frequency: 3.0
  controller_patience: 3.0
  meter_scoring: True

